<?php

/*************************************************************************

PHP Version: 5.0.4 Xampp
Class Name: Configuration Settings 
Description: Common configuration information. database name, pasword, domain name
Version Date: 1.0 21.09.2006      
Author: Pasan Rajapaksha
**************************************************************************/

class configurationsettings{

	public static $ROOT="/xampp/htdocs/downloadzone/";
	public static $Host = "localhost";
	public static $Database = "downloadzone";
	public static $Username = "root";
	public static $Password = "";
	public static $ErrorLog = "";

	public static $SMTP = "smtp1.slt.lk";
	public static $Admin_Email = "pasan14@gmail.com";
	public static $WEBSITENAME = "http://localhost/downloadzone/";
	
	public static $LATEST_HOST = "c:/xampp/htdocs/";
	public static $LATEST_URL = host;
	
	public static $host = "http://localhost/"; // respective img upload path

}
?>